<a href="https://colab.research.google.com/github/EroshBc/DataSceince/blob/main/Chapter2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2.1 **loading the MNIST dataset in keras**


In [26]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels),(test_images,test_labels) = mnist.load_data()

In [27]:
train_images.shape


(60000, 28, 28)

In [28]:
len(train_labels)

60000

In [29]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [30]:
test_images.shape


(10000, 28, 28)

In [31]:
len(test_labels)

10000

In [32]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

**The network architechture**

In [33]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation = "relu"),
    layers.Dense(10, activation = "softmax")
])

**The compilation step**

In [34]:
model.compile(optimizer = "rmsprop",
              loss = "sparse_categorical_crossentropy",
              metrics=["accuracy"])

**reshaping the image data - before training**

In [35]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32")/255
test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype("float32")/255

**Fitting the model**

In [36]:
model.fit(train_images,train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 6s 11ms/step - loss: 0.2553 - accuracy: 0.9259
Epoch 2/5
469/469 [==============================] - 5s 11ms/step - loss: 0.1041 - accuracy: 0.9691
Epoch 3/5
469/469 [==============================] - 4s 9ms/step - loss: 0.0684 - accuracy: 0.9797
Epoch 4/5
469/469 [==============================] - 6s 12ms/step - loss: 0.0490 - accuracy: 0.9848
Epoch 5/5
469/469 [==============================] - 4s 10ms/step - loss: 0.0367 - accuracy: 0.9887


Using the model to make predictions


In [37]:
test_digits = test_images[0:10]
prediction = model.predict(test_digits)
prediction[0]

1/1 [==============================] - 0s 51ms/step


array([7.1717748e-10, 1.5360702e-10, 1.8141971e-07, 2.5671510e-05,
       1.4682134e-13, 1.0682959e-09, 1.7350257e-15, 9.9997395e-01,
       5.9621250e-09, 7.2116450e-08], dtype=float32)

In [38]:
prediction[0].argmax()

7

In [39]:
prediction[0][7]

0.99997395

In [40]:
test_labels[0]

7

In [41]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test acc:{test_acc}")

313/313 [==============================] - 1s 3ms/step - loss: 0.0741 - accuracy: 0.9787
test acc:0.9786999821662903


***2.2***







scalar

In [42]:
import numpy as np
x=np.array(12)
x

array(12)

In [43]:
x.ndim

0

vector

In [45]:
x = np.array([12,3,6,4,7])
x

array([12,  3,  6,  4,  7])

In [46]:
x.ndim

1

In [47]:
from tensorflow.keras.datasets import mnist
(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

In [49]:
train_images.shape

(60000, 28, 28)

In [50]:
train_images.ndim

3

In [51]:
train_images.dtype

dtype('uint8')